### ISSUE TITLE
一点小小建议，V2 看到的，但是评论要绑定手机号，于是提 issue 了

### ISSUE THREAD

**Issue by skyf0cker** [Buzz2d0/nicu#1]
这个前两天就看到了，今天回复一下，这个创意我觉得很棒，看了一下代码，对于你说的彩色效果不佳，我觉得可以从以下两个方面优化一下：
1. 我看你 palette 直接用的内置的 websafe，这个可能会让展示效果不太好，可以通过 quantizer 针对 scale 后的每一帧进行 palette 的生成。（这个我自己尝试了一下，效果有提升）
2. 还有是不是可以加入 抖动，效果是不是会更好一些？（不确定，没有尝试）
https://blog.jln.co/%E4%BD%BF%E7%94%A8Go%E7%94%A2%E7%94%9F%E5%8B%95%E6%85%8Bgif/

@buzz2d0

**Comment by Buzz2d0** [comment]
thx, 暂时先不研究🤣

**Comment by ZhjGo** [comment]
> 这个前两天就看到了，今天回复一下，这个创意我觉得很棒，看了一下代码，对于你说的彩色效果不佳，我觉得可以从以下两个方面优化一下：
> 
> 1. 我看你 palette 直接用的内置的 websafe，这个可能会让展示效果不太好，可以通过 quantizer 针对 scale 后的每一帧进行 palette 的生成。（这个我自己尝试了一下，效果有提升）
> 2. 还有是不是可以加入 抖动，效果是不是会更好一些？（不确定，没有尝试）
>    https://blog.jln.co/%E4%BD%BF%E7%94%A8Go%E7%94%A2%E7%94%9F%E5%8B%95%E6%85%8Bgif/
> 
> @Buzz2d0

你好，我想问问第一点怎么实现的，能贴一下代码吗？我弄了一下，效果是好了，但是透明的部分变黑色了，不知道怎么弄成白色

**Comment by skyf0cker** [comment]
> 

这个是因为你最下面的 canvas 的 palette 的第一个颜色应该设置为 transparent。
因为底下的图片的 pixel 默认是 0，所以取到的颜色默认就是第一个，所以如果想让没有被后面图片覆盖住的地方显示透明，
就需要：
palette = append([]color.Color{color.Transparent}, palettte...)

代码的话，我没整理，现在不见得能跑，大概贴一下吧：
```go
                .......
                //  主要是这一段吧
		palettes := image.NewPaletted(rect, nil)
		quantizer := gogif.MedianCutQuantizer{NumColor: 64}
		quantizer.Quantize(palettes, rect, head, head.Rect.Min)

		var out = image.NewPaletted(rect, palettes.Palette)
		out.Palette = append([]color.Color{color.Transparent}, out.Palette...)
		out.Palette = append(out.Palette, srcimg.Palette...)
                .......
```
@ZhjGo

**Comment by skyf0cker** [comment]
当然这样组合 palette 的话，需要注意 quantizer 的 NumColor 还是要算一下的，避免超过 256，我这里写死是因为确定不会超

**Comment by ZhjGo** [comment]
@skyf0cker 感谢大佬解答
